### ISSUE TITLE
Add isCRN function

### ISSUE THREAD

**Issue by aeksco** [rcos/rpi-validator#1]
Might be nice to have a function that could validate CRNs:

```
64678
65173
64682
```

CRN must be numeric & 5 digits long - could validate numericality with the following:

```js
function isNumeric(n) {
  return !isNaN(parseFloat(n)) && isFinite(n);
}
``` 

Or simply use a regex and treat the CRN as a string

**Comment by jake-billings** [comment]
I'm trying to copy the style from https://www.npmjs.com/package/validator, so I'm planning on implementing everything as string validation (at least for the time being) for consistency. As a result, users of the library will have to pass string values in.

How's the follow regex-based function?
```js
function isCRN(input) {
    if (typeof input !== 'string') throw new TypeError('input to must be of type string');
    return /^\d{5}$/.test(input);
}
```

**Comment by aeksco** [comment]
Of course! Wrote this before I saw the rest of the library was strings only - makes sense to keep it consistent. Your implementation above looks great - open a PR and merge away! Don't forget to bump your version in `package.json` a [minor version](https://semver.org/) :+1:

**Comment by jake-billings** [comment]
Naw, I'm good committing to master.
